lsn req
sergey-berezin/441_2_prokofev pull request #2
Opened 2024-09-30 10:27 UTC by baindfrst

2024-10-07 10:01 UTC, sergey-berezin requested changes

2024-10-07 10:01 UTC, sergey-berezin commented on lib/Genom.cs
> +            GenomScore += CityMap[i][cityNumberConections[i]];
Нужно пояснение к этой строчке. Если CityMap[i][j] - это расстояние от города i до города j, то почему вы считаете длину маршрута как сумму расстояний от i-го города до cityNumberConections[j]?

2024-10-07 10:01 UTC, sergey-berezin commented on lib/Genom.cs
> +    public int CalculateGenomScore(int[][] CityMap)
Название Score неудачное. Обычно Score (баллы, очки) максимизируют, а вы - минимизируете.

2024-10-07 10:07 UTC, baindfrst commented on lib/Genom.cs
> +            GenomScore += CityMap[i][cityNumberConections[i]];
В cityNumberConections[i] находится индекс следующего города. Таким образом cityNumberConections начинается с первого города, который нужно посетить после стартового города с индексом 0

2024-10-07 10:23 UTC, sergey-berezin commented on lib/Genom.cs
> +            GenomScore += CityMap[i][cityNumberConections[i]];
Тогда расстояние должно вычисляться по формуле CityMap[0][cnc[0]] + CityMap[cnc[0]][cnc[1]] + CityMap[cnc[1]][cnc[2]] + ..., где cnc = сityNumberConections.

2024-10-07 10:39 UTC, baindfrst commented
я загрузил реквест с исправлениями в коде

2024-10-08 08:35 UTC, sergey-berezin requested changes

2024-10-08 08:35 UTC, sergey-berezin commented on lib/Genom.cs
> +        GenomScore = CityMap[0][cityNumberConections[0]];
Здесь должно быть расстояние между первым и последним городом: `CityMap[cityNumberConections[0]][cityNumberConections[cityNumberConections.Length - 1]]`

2024-10-08 08:35 UTC, sergey-berezin commented on lib/Genom.cs
> +            GenomScore += CityMap[cityNumberConections[i-1]][cityNumberConections[i]];
Такое изменение свойства в цикле неэффективно. Лучше сделать локальную переменную и в конце метода присвоить ёё `GenomScore`

2024-10-08 08:41 UTC, baindfrst commented on lib/Genom.cs
> +        GenomScore = CityMap[0][cityNumberConections[0]];
У меня в массиве CNC вроде как на последнем месте всегда стоит 0-ой город. Таким образом эта дорога учитывается в цикле. А вот как раз расстояние между 0 городом и следующим за ним обычным проходом по массиву без if-a не получить.

2024-10-08 08:50 UTC, baindfrst commented on lib/Genom.cs
> +            GenomScore += CityMap[cityNumberConections[i-1]][cityNumberConections[i]];
Понял, сегодня вечером подправлю

2024-10-09 09:01 UTC, baindfrst commented
Добрый день, вчера отправил ещё один пул реквест

2024-10-10 15:53 UTC, merged